### ISSUE TITLE
Potential to support Windows?

### ISSUE THREAD

**Issue by Bobbu** [LinusU/flutter_web_auth#107]
I am an enthusiastic consumer of this package, using a custom URI scheme to auth using box.com's API, targeting Android and iOS. I would love to target Windows to permit running natively on a Surface, but when I use the code as-is, it appears to hang on the redirect/webview portion.

**Comment by LinusU** [comment]
This is tracked in #22 and there is even an alternative package you can try out!

Unfortunately it's not super straight forward to implement this since an equivalent to [`ASWebAuthenticationSession`](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession) doesn't exist on the Windows platform.
