### ISSUE TITLE
Automate AndroidManifest.xml settings update

### ISSUE THREAD

**Issue by eldadfux** [LinusU/flutter_web_auth#23]
I am building a Flutter plugin that is using `flutter_web_auth` plugin to allow my users to authenticate using my own OAuth server (https://pub.dev/packages/appwrite).

I want to  allow my plugin users to set it up easily and since they never really need to change the `AndroidManifest.xml` because the `YOUR_CALLBACK_URL_SCHEME_HERE ` value is always the same (`appwrite-callback`), I wanted to know if i can automate this process so they won't have to handle with it.

Any ideas?

**Comment by LinusU** [comment]
Unfortunately, I think that you are going to run into problem if you try and reuse the same callback scheme. I once had both the test and normal build of an app I'm working on installed at the same time on an Android phone, both with the same callback scheme. When the authentication flow redirected back to my callback scheme, instead of notifying my app directly the system UI showed me a picker asking if I wanted to jump to "MyApp" or "MyApp [test]".

If one user have more than one app using appwrite it's going to be very confusing when performing the authentication flow...

I'd be happy if there are any workarounds for this!
