### ISSUE TITLE
plugin not working on ios 13

### ISSUE THREAD

**Issue by jingjiewei** [LinusU/flutter_web_auth#7]
use Xcode 11, on ios 13, got an error (com.apple.AuthenticationServices.WebAuthenticationSession error 2.), can reproduced using example code.  
Plugin works on ios 11 and ios 12

if downgrade to Xcode 10.2.1, then plugin works on ios 13, ios 12 and ios11

flutter version:  1.7.8+hotfix.3 stable

**Comment by alvynfash** [comment]
this is most likely due to breaking change in aswebAuth on iOS 13. it now requires a few things like context etc.

**Comment by cbenhagen** [comment]
@alvynfash do you mind coming up with a PR to fix that?

**Comment by alvynfash** [comment]
@cbenhagen Due to the changes in ios13  to refine the multi-app experience for iOS and iPadOS, we're now required to help the OS out when it's making the decision on where and how to display the OAuth Alert and Web login flow.  We now let the ASWebAuthenticationSession know which window is presenting the OAuth request by implementing ASWebAuthenticationPresentationContextProviding interface in your presenting View Controller which returns the relevant window in the presentationAnchor method.

I don't see how we can override the FlutterViewcontroller by default to implement this new Interface.

I however have a PR which solves the runtime issue when building with xcode 11 that uses the stable SF for ios13 as i assume apple will still modify this api very soon.

**Comment by jingjiewei** [comment]
> @cbenhagen Due to the changes in ios13 to refine the multi-app experience for iOS and iPadOS, we're now required to help the OS out when it's making the decision on where and how to display the OAuth Alert and Web login flow. We now let the ASWebAuthenticationSession know which window is presenting the OAuth request by implementing ASWebAuthenticationPresentationContextProviding interface in your presenting View Controller which returns the relevant window in the presentationAnchor method.
> 
> I don't see how we can override the FlutterViewcontroller by default to implement this new Interface.
> 
> I however have a PR which solves the runtime issue when building with xcode 11 that uses the stable SF for ios13 as i assume apple will still modify this api very soon.

@alvynfash thanks, that's very helpful

**Comment by LinusU** [comment]
Sorry for the delay, I've been out traveling for a while and my inbox has piled up 😅 

This should be fixed with 420a4066df2026d97d7c03d01f6aa7527b90087c, released as `0.1.2` :shipit: 

Let me know if this is still a problem!
